"""Auto-generate graded blockMeshDict files from high-level inputs.

The point of this module is to remove the single most tedious, error-prone part
of an OpenFOAM setup: hand-writing vertices, blocks, and grading. You give a
geometry preset and physical sizes (and, optionally, a target near-wall cell
height), and it returns a valid, boundary-layer-graded blockMeshDict.
"""

from __future__ import annotations

from typing import Dict, Tuple

PRESETS = {
    "channel": "2D rectangular channel/duct. Walls top & bottom, inlet/outlet left/right. Grading toward both walls.",
    "flatplate": "2D flat plate. No-slip bottom wall (graded), slip/farfield top, inlet/outlet.",
    "step": "2D backward-facing step (two blocks). Classic separation/reattachment benchmark.",
    "box": "Plain 3D box (uniform). Background mesh for snappyHexMesh / external flow.",
}


def _header(obj: str) -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by openfoam-mcp (auto blockMesh)                                  |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       dictionary;
    location    "system";
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""


def grading_from_first_cell(length: float, n_cells: int, first_cell: float) -> dict:
    """Compute the blockMesh simpleGrading value (last-cell/first-cell ratio)
    that places the first cell at ~`first_cell` height over an edge of physical
    `length` split into `n_cells`, using a geometric (constant expansion-ratio)
    distribution.
    """
    if length <= 0 or n_cells < 1 or first_cell <= 0:
        raise ValueError("length, n_cells and first_cell must be positive")
    uniform = length / n_cells
    if first_cell >= uniform:
        # Requested first cell is already >= uniform size; no grading needed.
        return {"grading": 1.0, "expansion_ratio": 1.0, "first_cell_m": uniform, "note": "uniform (target >= uniform cell size)"}

    def total(r: float) -> float:
        if abs(r - 1.0) < 1e-12:
            return first_cell * n_cells
        return first_cell * (r**n_cells - 1.0) / (r - 1.0)

    lo, hi = 1.0 + 1e-9, 5.0
    # ensure bracketing
    while total(hi) < length and hi < 100:
        hi *= 1.5
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if total(mid) < length:
            lo = mid
        else:
            hi = mid
    r = 0.5 * (lo + hi)
    grading = r ** (n_cells - 1)
    return {
        "grading": grading,
        "expansion_ratio": r,
        "first_cell_m": first_cell,
        "last_cell_m": first_cell * r ** (n_cells - 1),
    }


def _fmt(x: float) -> str:
    return f"{x:.6g}"


def _channel(lx, ly, lz, nx, ny, nz, gy) -> str:
    # symmetric double grading toward both y-walls; ny should be even
    half = max(ny // 2, 1)
    ygrad = f"( (0.5 0.5 {_fmt(gy)}) (0.5 0.5 {_fmt(1.0/gy)}) )" if gy != 1.0 else "1"
    grading = f"simpleGrading (1 {ygrad} 1)"
    body = _header("blockMeshDict") + f"""scale   1;

vertices
(
    (0     0     0)
    ({_fmt(lx)}  0     0)
    ({_fmt(lx)}  {_fmt(ly)}  0)
    (0     {_fmt(ly)}  0)
    (0     0     {_fmt(lz)})
    ({_fmt(lx)}  0     {_fmt(lz)})
    ({_fmt(lx)}  {_fmt(ly)}  {_fmt(lz)})
    (0     {_fmt(ly)}  {_fmt(lz)})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {2*half} {nz}) {grading}
);

edges ();

boundary
(
    inlet   {{ type patch; faces ((0 4 7 3)); }}
    outlet  {{ type patch; faces ((1 2 6 5)); }}
    walls   {{ type wall;  faces ((0 1 5 4) (3 7 6 2)); }}
    frontAndBack {{ type empty; faces ((0 3 2 1) (4 5 6 7)); }}
);

mergePatchPairs ();
"""
    return body


def _flatplate(lx, ly, lz, nx, ny, nz, gy) -> str:
    grading = f"simpleGrading (1 {_fmt(gy)} 1)"
    return _header("blockMeshDict") + f"""scale   1;

vertices
(
    (0     0     0)
    ({_fmt(lx)}  0     0)
    ({_fmt(lx)}  {_fmt(ly)}  0)
    (0     {_fmt(ly)}  0)
    (0     0     {_fmt(lz)})
    ({_fmt(lx)}  0     {_fmt(lz)})
    ({_fmt(lx)}  {_fmt(ly)}  {_fmt(lz)})
    (0     {_fmt(ly)}  {_fmt(lz)})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) {grading}
);

edges ();

boundary
(
    inlet   {{ type patch; faces ((0 4 7 3)); }}
    outlet  {{ type patch; faces ((1 2 6 5)); }}
    plate   {{ type wall;  faces ((0 1 5 4)); }}
    top     {{ type patch; faces ((3 7 6 2)); }}
    frontAndBack {{ type empty; faces ((0 3 2 1) (4 5 6 7)); }}
);

mergePatchPairs ();
"""


def _box(lx, ly, lz, nx, ny, nz) -> str:
    return _header("blockMeshDict") + f"""scale   1;

vertices
(
    (0     0     0)
    ({_fmt(lx)}  0     0)
    ({_fmt(lx)}  {_fmt(ly)}  0)
    (0     {_fmt(ly)}  0)
    (0     0     {_fmt(lz)})
    ({_fmt(lx)}  0     {_fmt(lz)})
    ({_fmt(lx)}  {_fmt(ly)}  {_fmt(lz)})
    (0     {_fmt(ly)}  {_fmt(lz)})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    inlet   {{ type patch; faces ((0 4 7 3)); }}
    outlet  {{ type patch; faces ((1 2 6 5)); }}
    top     {{ type patch; faces ((3 7 6 2)); }}
    bottom  {{ type patch; faces ((0 1 5 4)); }}
    frontAndBack {{ type patch; faces ((0 3 2 1) (4 5 6 7)); }}
);

mergePatchPairs ();
"""


def _step(lx, ly, lz, nx, ny, nz, gy) -> str:
    # Backward-facing step: inlet channel (upper half) expands into full-height duct.
    # Two blocks; step at x = lx/3, step height = ly/2.
    xs = lx / 3.0
    ys = ly / 2.0
    nx1 = max(nx // 3, 4)
    nx2 = max(nx - nx1, 4)
    ny_up = max(ny // 2, 4)
    ny_low = max(ny - ny_up, 4)
    # 3-block backward-facing step:
    #   B1 inlet channel (upper-left), B2 downstream upper, B3 downstream lower.
    # Vertices (z=0 plane 0-7, z=lz plane 8-15).
    return _header("blockMeshDict") + f"""scale   1;

vertices
(
    (0         {_fmt(ys)}  0)           // 0
    ({_fmt(xs)}  {_fmt(ys)}  0)         // 1
    ({_fmt(lx)}  {_fmt(ys)}  0)         // 2
    (0         {_fmt(ly)}  0)           // 3
    ({_fmt(xs)}  {_fmt(ly)}  0)         // 4
    ({_fmt(lx)}  {_fmt(ly)}  0)         // 5
    ({_fmt(xs)}  0         0)           // 6
    ({_fmt(lx)}  0         0)           // 7
    (0         {_fmt(ys)}  {_fmt(lz)})  // 8
    ({_fmt(xs)}  {_fmt(ys)}  {_fmt(lz)})// 9
    ({_fmt(lx)}  {_fmt(ys)}  {_fmt(lz)})// 10
    (0         {_fmt(ly)}  {_fmt(lz)})  // 11
    ({_fmt(xs)}  {_fmt(ly)}  {_fmt(lz)})// 12
    ({_fmt(lx)}  {_fmt(ly)}  {_fmt(lz)})// 13
    ({_fmt(xs)}  0         {_fmt(lz)})  // 14
    ({_fmt(lx)}  0         {_fmt(lz)})  // 15
);

blocks
(
    hex (0 1 4 3 8 9 12 11)  ({nx1} {ny_up} {nz})  simpleGrading (1 1 1)   // inlet upper-left
    hex (1 2 5 4 9 10 13 12) ({nx2} {ny_up} {nz})  simpleGrading (1 1 1)   // downstream upper
    hex (6 7 2 1 14 15 10 9) ({nx2} {ny_low} {nz}) simpleGrading (1 1 1)   // downstream lower
);

edges ();

boundary
(
    inlet  {{ type patch; faces ((0 8 11 3)); }}
    outlet {{ type patch; faces ((2 5 13 10) (7 2 10 15)); }}
    walls  {{ type wall;  faces (
        (3 11 12 4) (4 12 13 5)      // top wall
        (6 14 15 7)                  // bottom wall
        (0 1 9 8)                    // step top (under inlet)
        (6 1 9 14)                   // step face (vertical)
    ); }}
    frontAndBack {{ type empty; faces (
        (0 1 4 3) (1 2 5 4) (6 7 2 1)      // z = 0
        (8 9 12 11) (9 10 13 12) (14 15 10 9)  // z = lz
    ); }}
);

mergePatchPairs ();
"""


def generate(
    preset: str = "channel",
    length: float = 1.0,
    height: float = 0.2,
    depth: float = 0.05,
    cells_x: int = 60,
    cells_y: int = 40,
    cells_z: int = 1,
    first_cell_height: float = 0.0,
) -> Dict[str, object]:
    """Return {'blockMeshDict': <str>, 'meta': {...}} for a preset.

    If `first_cell_height` > 0, wall-normal grading is computed automatically so
    the near-wall cell matches that height (use first_cell_height from the
    `first_cell_height` calculator to hit a target y+).
    """
    preset = preset.lower()
    if preset not in PRESETS:
        raise ValueError(f"Unknown preset '{preset}'. Choose: {', '.join(PRESETS)}")

    grade_info = {"grading": 1.0}
    if first_cell_height and first_cell_height > 0 and preset != "box":
        # For 'channel' the wall-to-centre span is height/2; for others it's height.
        span = height / 2.0 if preset == "channel" else height
        n_wall = cells_y // 2 if preset == "channel" else cells_y
        grade_info = grading_from_first_cell(span, max(n_wall, 1), first_cell_height)
    gy = float(grade_info["grading"])

    if preset == "channel":
        content = _channel(length, height, depth, cells_x, cells_y, cells_z, gy)
    elif preset == "flatplate":
        content = _flatplate(length, height, depth, cells_x, cells_y, cells_z, gy)
    elif preset == "step":
        content = _step(length, height, depth, cells_x, cells_y, cells_z, gy)
    else:
        content = _box(length, height, depth, cells_x, cells_y, cells_z)

    return {
        "blockMeshDict": content,
        "meta": {
            "preset": preset,
            "domain_m": [length, height, depth],
            "cells": [cells_x, cells_y, cells_z],
            "wall_grading": grade_info,
        },
    }
