"""Generate runnable OpenFOAM case skeletons.

Templates target OpenFOAM (foundation v9-v12 / ESI v2306+ tutorial style using
``transportProperties`` + ``momentumTransport``/``turbulenceProperties``). Each
template writes a self-consistent case tree: ``system/``, ``constant/`` and
``0/`` with a simple single-block box mesh you can grow from.
"""

from __future__ import annotations

import os
from typing import Dict

SUPPORTED = {
    "simpleFoam": "Steady-state incompressible RANS (k-omega SST). Ducts, external aero, general.",
    "pimpleFoam": "Transient incompressible RANS (k-omega SST). Vortex shedding, unsteady flows.",
    "icoFoam": "Transient incompressible laminar. Low-Re teaching cases (cavity, low-Re pipe).",
}


def _header(cls: str, obj: str, loc: str) -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by openfoam-mcp                                                   |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    location    "{loc}";
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

"""


def _block_mesh(lx: float, ly: float, lz: float, nx: int, ny: int, nz: int) -> str:
    h = _header("dictionary", "blockMeshDict", "system")
    return h + f"""scale   1;

vertices
(
    (0     0     0)
    ({lx}  0     0)
    ({lx}  {ly}  0)
    (0     {ly}  0)
    (0     0     {lz})
    ({lx}  0     {lz})
    ({lx}  {ly}  {lz})
    (0     {ly}  {lz})
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges ();

boundary
(
    inlet   {{ type patch;  faces ((0 4 7 3)); }}
    outlet  {{ type patch;  faces ((1 2 6 5)); }}
    walls   {{ type wall;   faces ((0 1 5 4) (3 7 6 2)); }}
    frontAndBack {{ type empty; faces ((0 3 2 1) (4 5 6 7)); }}
);

mergePatchPairs ();
"""


def _control_dict(application: str, steady: bool, end_time: float, dt: float, write_interval,
                  solver_module: str = "") -> str:
    h = _header("dictionary", "controlDict", "system")
    adjustable = "no" if steady else "yes"
    # Foundation v11/v12: `foamRun` reads the physics module from `solver`.
    solver_line = f"solver          {solver_module};\n" if solver_module else ""
    return h + f"""application     {application};
{solver_line}startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {end_time};
deltaT          {dt};
writeControl    {"timeStep" if steady else "adjustableRunTime"};
writeInterval   {write_interval};
purgeWrite      0;
writeFormat     ascii;
writePrecision  7;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable true;
adjustTimeStep  {adjustable};
maxCo           1.0;
"""


def _fv_schemes(steady: bool) -> str:
    h = _header("dictionary", "fvSchemes", "system")
    ddt = "steadyState" if steady else "Euler"
    return h + f"""ddtSchemes      {{ default {ddt}; }}
gradSchemes     {{ default Gauss linear; }}
divSchemes
{{
    default             none;
    div(phi,U)          bounded Gauss linearUpwind grad(U);
    div(phi,k)          bounded Gauss upwind;
    div(phi,omega)      bounded Gauss upwind;
    div(phi,epsilon)    bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}}
laplacianSchemes {{ default Gauss linear corrected; }}
interpolationSchemes {{ default linear; }}
snGradSchemes   {{ default corrected; }}
wallDist        {{ method meshWave; }}
"""


def _fv_solution(solver: str, laminar: bool) -> str:
    h = _header("dictionary", "fvSolution", "system")
    steady = solver == "simpleFoam"
    fields = "U" if laminar else "(U|k|omega|epsilon|nuTilda)"

    if steady:
        # Steady SIMPLE: single-level solves, under-relaxation, residualControl.
        solvers = f"""solvers
{{
    p
    {{
        solver          GAMG;
        smoother        GaussSeidel;
        tolerance       1e-7;
        relTol          0.01;
    }}
    "{fields}"
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }}
}}
"""
        algo = """
SIMPLE
{
    nNonOrthogonalCorrectors 1;
    consistent      yes;
    residualControl { p 1e-4; U 1e-4; "(k|omega|epsilon)" 1e-4; }
}

relaxationFactors
{
    equations { U 0.9; ".*" 0.9; }
}
"""
    else:
        # Transient: needs *Final solves (pFinal, UFinal, ...) for the last corrector.
        solvers = f"""solvers
{{
    p
    {{
        solver          GAMG;
        smoother        GaussSeidel;
        tolerance       1e-7;
        relTol          0.01;
    }}
    pFinal
    {{
        solver          GAMG;
        smoother        GaussSeidel;
        tolerance       1e-7;
        relTol          0;
    }}
    "{fields}"
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0.1;
    }}
    "{fields}Final"
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-8;
        relTol          0;
    }}
}}
"""
        if solver == "icoFoam":
            algo = """
PISO
{
    nCorrectors     2;
    nNonOrthogonalCorrectors 1;
}
"""
        else:  # pimpleFoam and other PIMPLE solvers
            algo = """
PIMPLE
{
    nOuterCorrectors 1;
    nCorrectors      2;
    nNonOrthogonalCorrectors 1;
}
"""
    return h + solvers + algo


def _transport_properties(nu: float) -> str:
    h = _header("dictionary", "transportProperties", "constant")
    return h + f"""transportModel  Newtonian;
nu              [0 2 -1 0 0 0 0] {nu};
"""


def _physical_properties(nu: float) -> str:
    """OpenFOAM Foundation v11/v12: constant/physicalProperties (replaces
    transportProperties for the incompressibleFluid solver module)."""
    h = _header("dictionary", "physicalProperties", "constant")
    return h + f"""viscosityModel  constant;
nu              [0 2 -1 0 0 0 0] {nu};
"""


def _momentum_transport(laminar: bool) -> str:
    """Newer style (OpenFOAM Foundation v8+ / ESI v2006+): constant/momentumTransport."""
    h = _header("dictionary", "momentumTransport", "constant")
    if laminar:
        return h + """simulationType  laminar;
"""
    return h + """simulationType  RAS;

RAS
{
    model           kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
"""


def _turbulence_properties(laminar: bool) -> str:
    """Older style (OpenFOAM Foundation <=v7 / ESI <=v1912): constant/turbulenceProperties.

    Emitted alongside momentumTransport so a scaffolded case runs on any
    OpenFOAM version — each release reads the file it knows and ignores the other.
    """
    h = _header("dictionary", "turbulenceProperties", "constant")
    if laminar:
        return h + """simulationType  laminar;
"""
    return h + """simulationType  RAS;

RAS
{
    RASModel        kOmegaSST;
    turbulence      on;
    printCoeffs     on;
}
"""


def _field_U(velocity: float) -> str:
    h = _header("volVectorField", "U", "0")
    return h + f"""dimensions      [0 1 -1 0 0 0 0];
internalField   uniform (0 0 0);

boundaryField
{{
    inlet   {{ type fixedValue; value uniform ({velocity} 0 0); }}
    outlet  {{ type zeroGradient; }}
    walls   {{ type noSlip; }}
    frontAndBack {{ type empty; }}
}}
"""


def _field_p() -> str:
    h = _header("volScalarField", "p", "0")
    return h + """dimensions      [0 2 -2 0 0 0 0];
internalField   uniform 0;

boundaryField
{
    inlet   { type zeroGradient; }
    outlet  { type fixedValue; value uniform 0; }
    walls   { type zeroGradient; }
    frontAndBack { type empty; }
}
"""


def _field_scalar(obj: str, dims: str, internal: str, inlet: str, wall: str) -> str:
    h = _header("volScalarField", obj, "0")
    return h + f"""dimensions      {dims};
internalField   uniform {internal};

boundaryField
{{
    inlet   {{ type fixedValue; value uniform {inlet}; }}
    outlet  {{ type zeroGradient; }}
    walls   {{ {wall} }}
    frontAndBack {{ type empty; }}
}}
"""


FLAVORS = ("classic", "foundation-v12")


def build_case(
    solver: str = "simpleFoam",
    velocity: float = 10.0,
    nu: float = 1.5e-5,
    domain=(1.0, 0.2, 0.1),
    cells=(40, 20, 1),
    end_time: float = 1000.0,
    flavor: str = "classic",
) -> Dict[str, str]:
    """Return a mapping of {relative_path: file_content} for a case skeleton.

    flavor:
      - 'classic'        -> application <solver>; (simpleFoam/pimpleFoam/icoFoam)
                            with constant/transportProperties. Validated on
                            ESI v1912; works on ESI v2006+ and Foundation v8-v10.
      - 'foundation-v12' -> application foamRun; solver incompressibleFluid; with
                            constant/physicalProperties. Targets OpenFOAM
                            Foundation v11/v12 (the modular-solver framework).
    """
    if solver not in SUPPORTED:
        raise ValueError(f"Unsupported solver '{solver}'. Choose one of: {', '.join(SUPPORTED)}")
    flavor = flavor.lower()
    if flavor in ("v12", "foundation", "foamrun", "foundation-v11", "foundation-v12"):
        flavor = "foundation-v12"
    elif flavor in ("classic", "esi", "v1912", "foundation-v10"):
        flavor = "classic"
    else:
        raise ValueError(f"Unknown flavor '{flavor}'. Choose one of: {', '.join(FLAVORS)}")

    laminar = solver == "icoFoam"
    steady = solver == "simpleFoam"
    lx, ly, lz = domain
    nx, ny, nz = cells

    if steady:
        dt, wi = 1.0, 100
    elif solver == "pimpleFoam":
        dt, wi, end_time = 1e-3, 0.05, min(end_time, 1.0)
    else:  # icoFoam
        dt, wi, end_time = 5e-3, 0.1, min(end_time, 1.0)

    # Application / solver module differ by flavor.
    if flavor == "foundation-v12":
        application = "foamRun"
        solver_module = "incompressibleFluid"  # handles steady + transient + laminar
        # incompressibleFluid uses PIMPLE (not PISO) even for laminar transient.
        fv_solver = "pimpleFoam" if solver == "icoFoam" else solver
    else:
        application = solver
        solver_module = ""
        fv_solver = solver

    files: Dict[str, str] = {
        "system/blockMeshDict": _block_mesh(lx, ly, lz, nx, ny, nz),
        "system/controlDict": _control_dict(application, steady, end_time, dt, wi, solver_module),
        "system/fvSchemes": _fv_schemes(steady),
        "system/fvSolution": _fv_solution(fv_solver, laminar),
        "0/U": _field_U(velocity),
        "0/p": _field_p(),
    }

    # Viscosity/transport dict name differs by flavor.
    if flavor == "foundation-v12":
        files["constant/physicalProperties"] = _physical_properties(nu)
    else:
        files["constant/transportProperties"] = _transport_properties(nu)

    # Emit both turbulence-dictionary styles for cross-version compatibility.
    files["constant/momentumTransport"] = _momentum_transport(laminar)
    files["constant/turbulenceProperties"] = _turbulence_properties(laminar)

    if not laminar:
        # inlet turbulence: I=5%, l=0.07*ly
        k = 1.5 * (velocity * 0.05) ** 2
        length_scale = 0.07 * ly
        omega = k**0.5 / (0.09**0.25 * length_scale)
        nut = 0.09 * k**2 / (0.09**0.75 * k**1.5 / length_scale)
        wall_omega = "type omegaWallFunction; value uniform %.6g;" % omega
        files["0/k"] = _field_scalar(
            "k", "[0 2 -2 0 0 0 0]", f"{k:.6g}", f"{k:.6g}",
            f"type kqRWallFunction; value uniform {k:.6g};",
        )
        files["0/omega"] = _field_scalar(
            "omega", "[0 0 -1 0 0 0 0]", f"{omega:.6g}", f"{omega:.6g}", wall_omega,
        )
        files["0/nut"] = _field_scalar(
            "nut", "[0 2 -1 0 0 0 0]", "0", "0", "type nutkWallFunction; value uniform 0;",
        )

    return files


def write_case(case_dir: str, files: Dict[str, str]) -> list:
    """Write the file mapping to disk under ``case_dir``. Returns written paths."""
    written = []
    for rel, content in files.items():
        full = os.path.join(case_dir, rel)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(rel)
    return sorted(written)
